apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lego
  namespace: lego
  labels:
    app: lego
  annotations:
    kubernetes.io/ingress.class: "contour"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - secretName: tls-santa
    hosts:
    - santa.local
  rules:
  - host: santa.local
    http:
      paths:
      - path: /lego
        backend:
          serviceName: lego-v1
          servicePort: 80
      - path: /blog
        backend:
          serviceName: lego-blog
          servicePort: 80
