apiVersion: apps/v1
kind: Deployment
metadata:
  name: santa-v2
  namespace: santa
  labels:
    app: santa-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: santa-v2
  template:
    metadata:
      labels:
        app: santa-v2
    spec:
      containers:
      - name: santa-v1
        image: eu.gcr.io/khaly-221308/demo-contour
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "v2"
        - name: TEAM
          value: "Santa Ho Ho Ho"
        - name: ROUTING
          value: "false"
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: santa-v2
  namespace: santa
  labels:
    app: santa-v2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: santa-v2
