apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: santa-wildcard
  namespace: santa
spec:
  delegations:
    - secretName: wildcard-tls
      targetNamespaces:
      - "*" 
      