apiVersion: apps/v1
kind: Deployment
metadata:
  name: playmo-v2
  namespace: playmo
  labels:
    app: playmo-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playmo-v2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: playmo-v2
    spec:
      containers:
      - name: playmo-v2
        image: eu.gcr.io/khaly-221308/demo-contour
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        env:
        - name: VERSION
          value: "Home v2"
        - name: TEAM
          value: "Playmo"
        - name: LABEL
          value: "TEAM"
        - name: PORT
          value: "8080"
        - name: ROUTING
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: playmo-v2
  namespace: playmo
  labels:
    app: playmo-v2
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: playmo-v2
