apiVersion: apps/v1
kind: Deployment
metadata:
  name: playmo-v1
  namespace: playmo
  labels:
    app: playmo-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playmo-v1
  template:
    metadata:
      labels:
        app: playmo-v1
    spec:
      containers:
      - name: playmo-v1
        image: eu.gcr.io/khaly-221308/demo-contour
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "v1"
        - name: TEAM
          value: "Playmo"
        - name: PORT
          value: "8080"
        - name: ROUTING
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: playmo-v1
  namespace: playmo
  labels:
    app: playmo-v1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: playmo-v1
